// <auto-generated />
using CodeBridgePlatform.DbContext.DataLayer.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CodeBridgeGPT.DbContext.DataLayer.Migrations
{
    [DbContext(typeof(DataLayerContext))]
    [Migration("20250629193046_NewColumnUpdate")]
    partial class NewColumnUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeBridgeGPT.DbContext.DataLayer.Models.CodeBridgeGptResponseModel", b =>
                {
                    b.Property<string>("TaskResponseId")
                        .HasColumnType("text");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskResponseId");

                    b.ToTable("CodeBridgeGptDbResponse");
                });

            modelBuilder.Entity("CodeBridgeGPT.DbContext.DataLayer.Models.FilesModel", b =>
                {
                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeBridgeGptResponseModelTaskResponseId")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FilePath");

                    b.HasIndex("CodeBridgeGptResponseModelTaskResponseId");

                    b.ToTable("FilesModel");
                });

            modelBuilder.Entity("CodeBridgeGPT.DbContext.DataLayer.Models.FilesModel", b =>
                {
                    b.HasOne("CodeBridgeGPT.DbContext.DataLayer.Models.CodeBridgeGptResponseModel", null)
                        .WithMany("Files")
                        .HasForeignKey("CodeBridgeGptResponseModelTaskResponseId");
                });

            modelBuilder.Entity("CodeBridgeGPT.DbContext.DataLayer.Models.CodeBridgeGptResponseModel", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
